// ==========================================================================
// Tooth Clicker — built on Atom Design System
// ==========================================================================

const { useState, useEffect, useRef, useMemo, useCallback } = React;

// ---------- i18n ----------
const STRINGS = {
  es: {
    appName: 'Tooth Clicker',
    appSubtitle: 'Un experimento de Atom Labs',
    teeth: 'dientes',
    perSecond: 'por segundo',
    perClick: 'por click',
    clickMe: 'Haz click en el diente',
    clickBtn: 'Click',
    totalClicks: 'Clicks totales',
    totalTeeth: 'Dientes totales',
    timePlayed: 'Tiempo jugado',
    currentTeeth: 'Dientes actuales',
    goldenMsg: '¡Diente dorado! x7 durante 13 s',
    goldenActive: 'Multiplicador x7 activo',
    tabClick: 'Click',
    tabGen: 'Generadores',
    tabAch: 'Logros',
    tabPrestige: 'Prestigio',
    tabStats: 'Estadísticas',
    buy: 'Comprar',
    owned: 'Cantidad',
    produces: 'Produce',
    cost: 'Coste',
    locked: 'Bloqueado',
    unlockAt: 'Se desbloquea a',
    prestigeTitle: 'Sonrisa dorada',
    prestigeDesc: 'Reinicia todo el progreso a cambio de Sonrisas doradas permanentes. Cada una otorga +5 % de producción total.',
    prestigeEarn: 'Ganarás',
    prestigeHave: 'Actualmente tienes',
    prestigeBonus: 'Bonus actual',
    prestigeBtn: 'Reiniciar y prestigiar',
    prestigeLock: 'Necesitas al menos 1 sonrisa para prestigiar',
    confirmPrestige: '¿Seguro? Se reiniciará todo tu progreso.',
    ach_unlocked: 'Desbloqueado',
    ach_locked: 'Bloqueado',
    reset: 'Eliminar usuario',
    confirmReset: 'Si eliminas tu usuario perderás TODO el progreso del juego y tu puesto en el ranking. Esta acción no se puede deshacer. ¿Seguro?',
    lang: 'ES',
    save: '',
    saveNow: 'Guardar',
    savedJustNow: 'Guardado',
    savingLabel: 'Guardando…',
    autoSaveEvery: 'Guardado automático cada minuto',
    logout: 'Cerrar sesión',
    menuOptions: 'Opciones',
    clickPowerTitle: 'Mejoras de click',
    clickPowerSub: 'Aumenta cuántos dientes consigues por click',
    generatorsTitle: 'Generadores',
    generatorsSub: 'Producen dientes automáticamente cada segundo',
    achTitle: 'Logros',
    achSub: 'Recompensas por tus hitos. Cada uno otorga +1 % de producción permanente.',
    statsTitle: 'Estadísticas',
    soundOn: 'Sonido activado',
    soundOff: 'Sonido desactivado',
    toast_achieved: 'Logro desbloqueado',
    tabLeaderboard: 'Ranking',
    gateTabGame: 'Juego',
    gateTabLeaderboard: 'Ranking global',
    signOut: 'Cerrar sesión',
    // Gate
    gateTitle: 'Tooth Clicker',
    gateTagline: 'Un clicker de Atom Labs. Recoge dientes, abre clínicas, llega a la cima del ranking.',
    gateWelcomeBack: 'Bienvenido de vuelta',
    gateWelcomeBackSub: 'Continúa donde lo dejaste.',
    gateNameLabel: 'Tu nombre',
    gateNamePlaceholder: 'Escribe tu nombre',
    gateLangLabel: 'Idioma',
    gatePlay: 'Empezar a jugar',
    gateContinue: 'Continuar partida',
    gateNewGame: 'Nueva partida',
    gateLocal: '',
    gateExisting: 'Este nombre ya está en uso en el ranking. Elige otro.',
    welcomeBackTitle: 'Bienvenido de vuelta',
    welcomeBackMsg: 'Mientras estabas fuera conseguiste',
    welcomeBackPatients: 'pacientes felices',
    welcomeBackCap: 'Las ganancias offline están limitadas a 2 horas.',
    welcomeBackContinue: 'Continuar jugando',
    gateDelete: 'Borrar',
    gateConfirmDelete: '¿Borrar la partida de',
    // Leaderboard
    lbTitle: 'Ranking global',
    lbSub: 'Ranking global en tiempo real. Se ordena por prestigio y luego por dientes totales.',
    lbEmpty: 'Aún no hay jugadores en el ranking. ¡Sé el primero!',
    lbLoading: 'Cargando ranking…',
    lbError: 'No se pudo conectar con el servidor',
    lbRetry: 'Reintentar',
    lbRefresh: 'Actualizar',
    lbLastUpdate: 'Actualizado hace',
    lbSyncing: 'Sincronizando…',
    lbSynced: 'Sincronizado',
    lbOffline: 'Sin conexión',
    lbSec: 's',
    lbRank: '#',
    lbPlayer: 'Jugador',
    lbPrestige: 'Prestigio',
    lbTotal: 'Dientes totales',
    lbTime: 'Tiempo',
    lbYou: 'Tú',
  },
  en: {
    appName: 'Tooth Clicker',
    appSubtitle: 'An Atom Labs experiment',
    teeth: 'teeth',
    perSecond: 'per second',
    perClick: 'per click',
    clickMe: 'Click the tooth',
    clickBtn: 'Click',
    totalClicks: 'Total clicks',
    totalTeeth: 'All-time teeth',
    timePlayed: 'Time played',
    currentTeeth: 'Current teeth',
    goldenMsg: 'Golden tooth! x7 for 13 s',
    goldenActive: 'x7 multiplier active',
    tabClick: 'Click',
    tabGen: 'Generators',
    tabAch: 'Achievements',
    tabPrestige: 'Prestige',
    tabStats: 'Stats',
    buy: 'Buy',
    owned: 'Owned',
    produces: 'Produces',
    cost: 'Cost',
    locked: 'Locked',
    unlockAt: 'Unlocks at',
    prestigeTitle: 'Golden smile',
    prestigeDesc: 'Reset all progress in exchange for permanent Golden smiles. Each grants +5 % to total production.',
    prestigeEarn: 'You will earn',
    prestigeHave: 'You currently have',
    prestigeBonus: 'Current bonus',
    prestigeBtn: 'Reset and prestige',
    prestigeLock: 'You need at least 1 smile to prestige',
    confirmPrestige: 'Are you sure? All progress will reset.',
    ach_unlocked: 'Unlocked',
    ach_locked: 'Locked',
    reset: 'Delete user',
    confirmReset: 'Deleting your user will erase ALL game progress and your leaderboard position. This cannot be undone. Are you sure?',
    lang: 'EN',
    save: '',
    saveNow: 'Save',
    savedJustNow: 'Saved',
    savingLabel: 'Saving…',
    autoSaveEvery: 'Auto-saved every minute',
    logout: 'Log out',
    menuOptions: 'Options',
    clickPowerTitle: 'Click upgrades',
    clickPowerSub: 'Increase how many teeth each click produces',
    generatorsTitle: 'Generators',
    generatorsSub: 'They produce teeth automatically every second',
    achTitle: 'Achievements',
    achSub: 'Rewards for your milestones. Each grants +1 % permanent production.',
    statsTitle: 'Stats',
    soundOn: 'Sound on',
    soundOff: 'Sound off',
    toast_achieved: 'Achievement unlocked',
    tabLeaderboard: 'Leaderboard',
    gateTabGame: 'Game',
    gateTabLeaderboard: 'Global leaderboard',
    signOut: 'Sign out',
    // Gate
    gateTitle: 'Tooth Clicker',
    gateTagline: 'An Atom Labs clicker. Collect teeth, open clinics, top the leaderboard.',
    gateWelcomeBack: 'Welcome back',
    gateWelcomeBackSub: 'Continue where you left off.',
    gateNameLabel: 'Your name',
    gateNamePlaceholder: 'Type your name',
    gateLangLabel: 'Language',
    gatePlay: 'Start playing',
    gateContinue: 'Continue game',
    gateNewGame: 'New game',
    gateLocal: '',
    gateExisting: 'This name is already in the leaderboard. Pick another.',
    welcomeBackTitle: 'Welcome back',
    welcomeBackMsg: 'While you were away you earned',
    welcomeBackPatients: 'happy patients',
    welcomeBackCap: 'Offline earnings are capped at 2 hours.',
    welcomeBackContinue: 'Keep playing',
    gateDelete: 'Delete',
    gateConfirmDelete: "Delete the save for",
    // Leaderboard
    lbTitle: 'Global leaderboard',
    lbSub: 'Live global ranking. Sorted by prestige, then all-time teeth.',
    lbEmpty: 'No players on the leaderboard yet. Be the first!',
    lbLoading: 'Loading leaderboard…',
    lbError: "Couldn't reach the server",
    lbRetry: 'Retry',
    lbRefresh: 'Refresh',
    lbLastUpdate: 'Updated',
    lbSyncing: 'Syncing…',
    lbSynced: 'Synced',
    lbOffline: 'Offline',
    lbSec: 's ago',
    lbRank: '#',
    lbPlayer: 'Player',
    lbPrestige: 'Prestige',
    lbTotal: 'All-time teeth',
    lbTime: 'Time',
    lbYou: 'You',
  },
};

// ---------- Game config ----------
// GENERATORS / CLICK_UPGRADES / ACHIEVEMENTS live in content.jsx.
// Helpers (genCost, formatNumWithMode, formatTime, playTone, computeClickPower) also come from content.jsx.
const GENERATORS = window.GENERATORS;
const CLICK_UPGRADES = window.CLICK_UPGRADES;
const ACHIEVEMENTS = window.ACHIEVEMENTS;
const genCost = window.genCost;
const formatTime = window.formatTime;
const playTone = window.playTone;
const computeClickPower = window.computeClickPower;

// formatNum is mode-aware and reads the user's chosen mode + language from
// window.__numFormat / window.__lang (set by <Game>). Falls back to short/es.
function formatNum(n, modeOverride, langOverride) {
  const mode = modeOverride || window.__numFormat || 'short';
  const lang = langOverride || window.__lang || 'es';
  return window.formatNumWithMode(n, mode, lang);
}

Object.assign(window, { STRINGS, formatNum });
