// Tooth Clicker — i18n strings + formatNum helper
const STRINGS = {
  es: {
    appName: 'Tooth Clicker', appSubtitle: 'Un experimento de Atom Labs',
    teeth: 'dientes', perSecond: 'por segundo', perClick: 'por click',
    clickMe: 'Haz click en el diente', totalClicks: 'Clicks totales',
    totalTeeth: 'Dientes totales', timePlayed: 'Tiempo jugado', currentTeeth: 'Dientes actuales',
    goldenMsg: '¡Diente dorado! x7 durante 13 s', goldenActive: 'Multiplicador x7 activo',
    tabClick: 'Click', tabGen: 'Generadores', tabAch: 'Logros',
    tabPrestige: 'Prestigio', tabStats: 'Estadísticas', tabLeaderboard: 'Ranking',
    buy: 'Comprar', owned: 'Cantidad', produces: 'Produce', cost: 'Coste',
    locked: 'Bloqueado', unlockAt: 'Se desbloquea a',
    prestigeTitle: 'Sonrisa dorada',
    prestigeDesc: 'Reinicia todo el progreso a cambio de Sonrisas doradas permanentes. Cada una otorga +5 % de producción total.',
    prestigeEarn: 'Ganarás', prestigeHave: 'Actualmente tienes', prestigeBonus: 'Bonus actual',
    prestigeBtn: 'Reiniciar y prestigiar', prestigeLock: 'Necesitas al menos 1 sonrisa para prestigiar',
    confirmPrestige: '¿Seguro? Se reiniciará todo tu progreso.',
    ach_unlocked: 'Desbloqueado', ach_locked: 'Bloqueado',
    reset: 'Eliminar usuario',
    confirmReset: 'Si eliminas tu usuario perderás TODO el progreso del juego y tu puesto en el ranking. Esta acción no se puede deshacer. ¿Seguro?',
    lang: 'ES', saveNow: 'Guardar', savedJustNow: 'Guardado',
    logout: 'Cerrar sesión', menuOptions: 'Opciones',
    clickPowerTitle: 'Mejoras de click', clickPowerSub: 'Aumenta cuántos dientes consigues por click',
    upgradeFilterAll: 'Todas', upgradeFilterUnlocked: 'Desbloqueadas', upgradeFilterLocked: 'Bloqueadas',
    generatorsTitle: 'Generadores', generatorsSub: 'Producen dientes automáticamente cada segundo',
    achTitle: 'Logros', achSub: 'Recompensas por tus hitos. Cada uno otorga +1 % de producción permanente.',
    statsTitle: 'Estadísticas', soundOn: 'Sonido activado', soundOff: 'Sonido desactivado',
    toast_achieved: 'Logro desbloqueado', prestige: 'Prestigio',
    gateTabGame: 'Juego', gateTabLeaderboard: 'Ranking global',
    gateTitle: 'Tooth Clicker',
    gateTagline: 'Un clicker de Atom Labs. Recoge dientes, abre clínicas, llega a la cima del ranking.',
    gateWelcomeBack: 'Bienvenido de vuelta', gateWelcomeBackSub: 'Continúa donde lo dejaste.',
    gateNameLabel: 'Tu nombre', gateNamePlaceholder: 'Escribe tu nombre',
    gatePlay: 'Empezar a jugar', gateContinue: 'Continuar partida',
    gateExisting: 'Este nombre ya está en uso en el ranking. Elige otro.',
    welcomeBackTitle: 'Bienvenido de vuelta', welcomeBackMsg: 'Mientras estabas fuera conseguiste',
    welcomeBackPatients: 'pacientes felices', welcomeBackCap: 'Las ganancias offline están limitadas a 2 horas.',
    welcomeBackContinue: 'Continuar jugando',
    lbTitle: 'Ranking global', lbSub: 'Ranking global en tiempo real.',
    lbEmpty: 'Aún no hay jugadores en el ranking. ¡Sé el primero!',
    lbLoading: 'Cargando ranking…', lbError: 'No se pudo conectar con el servidor',
    lbRetry: 'Reintentar', lbRefresh: 'Actualizar', lbLastUpdate: 'Actualizado hace',
    lbSec: 's', lbRank: '#', lbPlayer: 'Jugador', lbPrestige: 'Prestigio', lbTotal: 'Dientes totales', lbYou: 'Tú',
  },
  en: {
    appName: 'Tooth Clicker', appSubtitle: 'An Atom Labs experiment',
    teeth: 'teeth', perSecond: 'per second', perClick: 'per click',
    clickMe: 'Click the tooth', totalClicks: 'Total clicks',
    totalTeeth: 'All-time teeth', timePlayed: 'Time played', currentTeeth: 'Current teeth',
    goldenMsg: 'Golden tooth! x7 for 13 s', goldenActive: 'x7 multiplier active',
    tabClick: 'Click', tabGen: 'Generators', tabAch: 'Achievements',
    tabPrestige: 'Prestige', tabStats: 'Stats', tabLeaderboard: 'Leaderboard',
    buy: 'Buy', owned: 'Owned', produces: 'Produces', cost: 'Cost',
    locked: 'Locked', unlockAt: 'Unlocks at',
    prestigeTitle: 'Golden smile',
    prestigeDesc: 'Reset all progress in exchange for permanent Golden smiles. Each grants +5 % to total production.',
    prestigeEarn: 'You will earn', prestigeHave: 'You currently have', prestigeBonus: 'Current bonus',
    prestigeBtn: 'Reset and prestige', prestigeLock: 'You need at least 1 smile to prestige',
    confirmPrestige: 'Are you sure? All progress will reset.',
    ach_unlocked: 'Unlocked', ach_locked: 'Locked',
    reset: 'Delete user',
    confirmReset: 'Deleting your user will erase ALL game progress and your leaderboard position. This cannot be undone. Are you sure?',
    lang: 'EN', saveNow: 'Save', savedJustNow: 'Saved',
    logout: 'Log out', menuOptions: 'Options',
    clickPowerTitle: 'Click upgrades', clickPowerSub: 'Increase how many teeth each click produces',
    upgradeFilterAll: 'All', upgradeFilterUnlocked: 'Unlocked', upgradeFilterLocked: 'Locked',
    generatorsTitle: 'Generators', generatorsSub: 'They produce teeth automatically every second',
    achTitle: 'Achievements', achSub: 'Rewards for your milestones. Each grants +1 % permanent production.',
    statsTitle: 'Stats', soundOn: 'Sound on', soundOff: 'Sound off',
    toast_achieved: 'Achievement unlocked', prestige: 'Prestige',
    gateTabGame: 'Game', gateTabLeaderboard: 'Global leaderboard',
    gateTitle: 'Tooth Clicker',
    gateTagline: 'An Atom Labs clicker. Collect teeth, open clinics, top the leaderboard.',
    gateWelcomeBack: 'Welcome back', gateWelcomeBackSub: 'Continue where you left off.',
    gateNameLabel: 'Your name', gateNamePlaceholder: 'Type your name',
    gatePlay: 'Start playing', gateContinue: 'Continue game',
    gateExisting: 'This name is already in the leaderboard. Pick another.',
    welcomeBackTitle: 'Welcome back', welcomeBackMsg: 'While you were away you earned',
    welcomeBackPatients: 'happy patients', welcomeBackCap: 'Offline earnings are capped at 2 hours.',
    welcomeBackContinue: 'Keep playing',
    lbTitle: 'Global leaderboard', lbSub: 'Live global ranking.',
    lbEmpty: 'No players yet. Be the first!',
    lbLoading: 'Loading leaderboard…', lbError: "Couldn't reach the server",
    lbRetry: 'Retry', lbRefresh: 'Refresh', lbLastUpdate: 'Updated',
    lbSec: 's ago', lbRank: '#', lbPlayer: 'Player', lbPrestige: 'Prestige', lbTotal: 'All-time teeth', lbYou: 'You',
  },
};

function formatNum(n, modeOverride, langOverride) {
  const mode = modeOverride || window.__numFormat || 'short';
  const lang = langOverride || window.__lang || 'es';
  return window.formatNumWithMode(n, mode, lang);
}

// Tooth stage progression (prestige-based)
const TOOTH_STAGES = [
  { img: 'uploads/tooth1.png',             prestige: 0,       es: 'Diente descompuesto',  en: 'Rotten tooth' },
  { img: 'uploads/tooth2.png',             prestige: 1,       es: 'Diente con caries',    en: 'Cavity tooth' },
  { img: 'uploads/tooth3.png',             prestige: 5,       es: 'Diente deteriorado',   en: 'Damaged tooth' },
  { img: 'uploads/tooth4.png',             prestige: 10,      es: 'Diente preocupado',    en: 'Worried tooth' },
  { img: 'uploads/tooth5.png',             prestige: 25,      es: 'Diente amarillo',      en: 'Yellow tooth' },
  { img: 'uploads/tooth6.png',             prestige: 50,      es: 'Diente apagado',       en: 'Dull tooth' },
  { img: 'uploads/tooth7.png',             prestige: 100,     es: 'Diente neutral',       en: 'Neutral tooth' },
  { img: 'uploads/tooth8.png',             prestige: 250,     es: 'Diente contento',      en: 'Content tooth' },
  { img: 'uploads/tooth9.png',             prestige: 500,     es: 'Diente feliz',         en: 'Happy tooth' },
  { img: 'uploads/tooth10.png',            prestige: 1000,    es: 'Diente muy feliz',     en: 'Very happy tooth' },
  { img: 'uploads/tooth11.png',            prestige: 2500,    es: 'Diente brillante',     en: 'Bright tooth' },
  { img: 'uploads/tooth12.png',            prestige: 5000,    es: 'Diente carcajada',     en: 'Laughing tooth' },
  { img: 'uploads/tooth13-c01eb4d6.png',   prestige: 10000,   es: 'Diente radiante',      en: 'Radiant tooth' },
  { img: 'uploads/tooth14.png',            prestige: 25000,   es: 'Diente estrella',      en: 'Star tooth' },
  { img: 'uploads/tooth15.png',            prestige: 75000,   es: 'Diente celestial',     en: 'Celestial tooth' },
  { img: 'uploads/tooth16.png',            prestige: 200000,  es: 'Diente legendario',    en: 'Legendary tooth' },
  { img: 'uploads/tooth17.png',            prestige: 500000,  es: 'Diente supremo',       en: 'Supreme tooth' },
  { img: 'uploads/tooth18.png',            prestige: 1000000, es: 'Diente definitivo',    en: 'Ultimate tooth' },
];

function getToothStage(prestige) {
  let stage = TOOTH_STAGES[0];
  for (const s of TOOTH_STAGES) { if ((prestige || 0) >= s.prestige) stage = s; }
  return stage;
}

Object.assign(window, { STRINGS, formatNum, TOOTH_STAGES, getToothStage });
