const fs = require('fs');
let code = fs.readFileSync('app.jsx', 'utf8');
code = code.replace('return (', `
  console.log("Checking components:");
  console.log("LedMarquee", typeof LedMarquee);
  console.log("AboutModal", typeof AboutModal);
  console.log("BossMarquee", typeof BossMarquee);
  console.log("FallingTeethSimulation", typeof FallingTeethSimulation);
  console.log("FeedbackModal", typeof FeedbackModal);
  console.log("FloatingBonus", typeof FloatingBonus);
  console.log("Modal", typeof Modal);
  console.log("MusicFloatingBtn", typeof MusicFloatingBtn);
  console.log("MusicPlayerModal", typeof MusicPlayerModal);
  console.log("PrestigeConfetti", typeof PrestigeConfetti);
  console.log("window.AcademyUpgradeRow", typeof window.AcademyUpgradeRow);
  console.log("window.AchievementCard", typeof window.AchievementCard);
  console.log("window.AdminAutoClicker", typeof window.AdminAutoClicker);
  console.log("window.AdminLayout", typeof window.AdminLayout);
  console.log("window.AntiCheatModal", typeof window.AntiCheatModal);
  console.log("window.ClickUpgradeRow", typeof window.ClickUpgradeRow);
  console.log("window.GameTour", typeof window.GameTour);
  console.log("window.Gate", typeof window.Gate);
  console.log("window.GeneratorRow", typeof window.GeneratorRow);
  console.log("window.LeaderboardPanel", typeof window.LeaderboardPanel);
  console.log("window.MenuDivider", typeof window.MenuDivider);
  console.log("window.MenuItem", typeof window.MenuItem);
  console.log("window.Modal", typeof window.Modal);
  console.log("window.Odometer", typeof window.Odometer);
  console.log("window.SmartTooltip", typeof window.SmartTooltip);
  console.log("window.StatTile", typeof window.StatTile);
  console.log("window.StatsGroup", typeof window.StatsGroup);
  console.log("window.StoreUpgradeIcon", typeof window.StoreUpgradeIcon);
  console.log("window.TabBar", typeof window.TabBar);
  console.log("window.Toast", typeof window.Toast);
  console.log("window.Tooth3DViewer", typeof window.Tooth3DViewer);
  console.log("window.ToothbrushRing", typeof window.ToothbrushRing);
  return (
`);
fs.writeFileSync('app.jsx', code);
